import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — PlotTwist",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen py-16 px-4">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="text-[#9ca3af] hover:text-yellow-400 transition-colors text-sm mb-6 inline-block">
          ← Back to Home
        </Link>
        <h1 className="font-title text-3xl font-bold text-[#f0ece8] mb-6">Terms of Service</h1>
        <div className="card-glass rounded-2xl border border-white/8 p-6 text-[#9ca3af] text-sm leading-relaxed space-y-4">
          <p><strong className="text-[#f0ece8]">Entertainment Only:</strong> PlotTwist is fictional entertainment. Nothing generated by PlotTwist constitutes psychological analysis, personality assessment, future prediction, medical advice, legal advice, or financial advice.</p>
          <h2 className="font-title text-xl text-[#f0ece8] mt-4">Usage</h2>
          <p>You may use PlotTwist for personal entertainment. You agree not to use the service to generate harmful, defamatory, or harassing content about real individuals. All results are fictional.</p>
          <h2 className="font-title text-xl text-[#f0ece8] mt-4">Content</h2>
          <p>Generated stories are fictional entertainment. PlotTwist is not responsible for how users interpret or share generated content. Content is family-friendly and should not be used to bully or harass others.</p>
          <h2 className="font-title text-xl text-[#f0ece8] mt-4">No Warranties</h2>
          <p>PlotTwist is provided as-is for entertainment purposes. We make no claims about accuracy, completeness, or psychological validity of any generated content.</p>
          <p className="text-xs text-[#6b7280] mt-6">Last updated: 2026</p>
        </div>
      </div>
    </div>
  );
}
